name: Build React App

on:
  push:
    branches: [main]

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@4
        with:
          node-version: 18.x

      - name: Install dependences
        run: npm install

      - name: Build
        run: npm run build
