name: Deploy React App

on:
  workflow_dispatch:

jobs:
  deploy-react:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: build-artifact
          path: artifact
          run-id: 34645826752

      - name: Disploy structure of downloaded files
        run: ls -R artifact
