name: Step Output

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set Output
        id: set-output
        shell: bash
        run: |
          echo "name=andrew" >> $GITHUB_OUTPUT
          echo "age=37" >> $GITHUB_OUTPUT

      - name: set Output 2
        id: set-output-2
        shell: bash
        run: |
          echo "salary=50000" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo "The value of output name is ${{steps.set-output.outputs.name}}"
          echo "The value of output age is ${{steps.set-output.outputs.age}}"
          echo "The value of output salary is ${{steps.set-output-2.outputs.salary}}"
